### PR TITLE
Adding script to check all agda and lagda files are type-checked

### PR DESCRIPTION
**Pull request by Ali-Hill**
At the moment I test this with 

nix-build -A agdaLedger

Currently on master this leaves the log:

```
error: builder for '/nix/store/smzlnywaw8bhb47g4y3g62p64brlab1l-Agda-ledger-0.1.drv' failed with exit code 1;
       last 10 log lines:
       >  Checking MidnightExample.HSLedger (/private/tmp/nix-build-Agda-ledger-0.1.drv-0/src/MidnightExample/HSLedger.agda).
       >   Checking MidnightExample.Types (/private/tmp/nix-build-Agda-ledger-0.1.drv-0/src/MidnightExample/Types.agda).
       > installing
       > ./Interface/Show.agdai doesn't exist
       > ./Interface/Contains.agdai doesn't exist
       > ./Interface/Default.agdai doesn't exist
       > ./Test/ArgTurningIntoMeta.agdai doesn't exist
       > ./BooleanAlgebra.agdai doesn't exist
       > ./Data/List/Ext.agdai doesn't exist
       > ./MidnightExample/PDF.agdai doesn't exist
       For full logs, run 'nix log /nix/store/smzlnywaw8bhb47g4y3g62p64brlab1l-Agda-ledger-0.1.drv'.
```

### CODE REVIEW

**Comment by WhatisRT** [comment]
If you want you can review #53 first and then rebase on that, then you hopefully shouldn't see any failures

**Comment by Ali-Hill** [comment]
After doing that there are still 2 files that aren't type-checked. 

       > ./BooleanAlgebra.agdai doesn't exist
       > ./Data/List/Ext.agdai doesn't exist

**Comment by WhatisRT** [comment]
OK. They're also useless at this point, so I'll remove them as well in my PR

**Comment by WhatisRT** [comment]
Ah, you've already merged that one. Then let me just remove them here

**Review by WhatisRT — APPROVED** [review]
LGTM!

**Comment by williamdemeo** [comment]
@Ali-Hill @WhatisRT I realize this is already reviewed and merged (nice job, by the way!), but I just wanted to add a comment.

The way I normally generate `src/Everything.agda` is by doing `make Everything.agda` with the following entry in `Makefile`:

```
Everything.agda:
	@echo "target: $@ prereq: $<"
	@echo "module Everything where\n" > src/Everything.agda
	git ls-tree --full-tree -r --name-only HEAD | grep '^src/[^\.]*.lagda' | sed -e 's|^src/[/]*|import |' -e 's|/|.|g' -e 's/.lagda//' -e '/import Everything/d' | LC_COLLATE='C' sort >> src/Everything.agda
```

When I add the above to `Makefile` on the latest master, and invoke `make Everything.agda`, the following are the contents of `src/Everything.agda`:

```agda
module Everything where

import Ledger.Address
import Ledger.Chain
import Ledger.Crypto
import Ledger.Ledger
import Ledger.NewPP
import Ledger.PDF
import Ledger.PPUp
import Ledger.PParams
import Ledger.Script
import Ledger.Transaction
import Ledger.Utxo
import Ledger.Utxo.Properties
import Ledger.Utxow
import MidnightExample.Ledger
import MidnightExample.PDF
```

This adds all the modules, whether they're needed or not, so perhaps this is a useful complement to Alastair's script which should be run before `make Everything.agda` to ensure nothing gets added to the resulting `src/Everything.agda` unnecessarily.  What do you think?  Should I add an `Everything.agda` entry to the `Makefile`?

**Comment by williamdemeo** [comment]
I just noticed, the Makefile entry above only gets modules from `*.lagda` files.  If I add a similar `git ls-tree` line for `*.agda` files, I get the complete list of modules (I think), plus a couple of lines that we probably don't want (like `import latex.sty`, which I guess was generated from `latex/agda.sty` 😠):

```
module Everything where

import Ledger.Address
import Ledger.Chain
import Ledger.Crypto
import Ledger.Ledger
import Ledger.NewPP
import Ledger.PDF
import Ledger.PPUp
import Ledger.PParams
import Ledger.Script
import Ledger.Transaction
import Ledger.Utxo
import Ledger.Utxo.Properties
import Ledger.Utxow
import MidnightExample.Ledger
import MidnightExample.PDF
import Algebra.Literals
import Axiom.Set
import Axiom.Set.Factor
import Axiom.Set.List
import Axiom.Set.Map
import Axiom.Set.Properties
import Axiom.Set.Rel
import Axiom.Set.Sum
import Data.List.Ext.Properties
import Foreign.Convertible
import Interface.ComputationalRelation
import Interface.DecEq.Ext
import Interface.DecRel
import Interface.Decidable.Instance
import Interface.Hashable
import Ledger-ledger-executable-spec.cabal
import Ledger-lib
import Ledger.Epoch
import Ledger.Foreign.HSLedger
import Ledger.Foreign.LedgerTypes
import Ledger.Prelude
import Ledger.Utxow.Properties
import MidnightExample-ledger-executable-spec.cabal
import MidnightExample.HSLedger
import MidnightExample.Types
import MyDebugOptions
import Prelude
import PreludeImports
import Tactic.DeriveComp
import Test.GetType
import latex.sty
```

**Comment by williamdemeo** [comment]
The unwanted lines are:
```
import Ledger-ledger-executable-spec.cabal
import Ledger-lib
import MidnightExample-ledger-executable-spec.cabal
import latex.sty
```
once those are removed, the list of modules above type-checks. 👍🏼

**Comment by williamdemeo** [comment]
Finally, the correct Makefile entry is

```
Everything.agda:
	@echo "target: $@ prereq: $<"
	@echo "module Everything where\n" > src/Everything.agda
	git ls-tree --full-tree -r --name-only HEAD | find . -name "*.*agda" | sed -e 's|/|.|g' -e 's/.lagda//' -e 's/.agda//' -e 's/..src./import /' -e '/import Everything/d' | LC_COLLATE='C' sort >> src/Everything.agda
```

With this addition, doing `make Everything.agda` on master results in a file `src/Everything.agda` with the following contents:

```
module Everything where

import Algebra.Literals
import Axiom.Set
import Axiom.Set.Factor
import Axiom.Set.List
import Axiom.Set.Map
import Axiom.Set.Properties
import Axiom.Set.Rel
import Axiom.Set.Sum
import Data.List.Ext.Properties
import Foreign.Convertible
import Interface.ComputationalRelation
import Interface.DecEq.Ext
import Interface.DecRel
import Interface.Decidable.Instance
import Interface.Hashable
import Ledger.Address
import Ledger.Chain
import Ledger.Crypto
import Ledger.Epoch
import Ledger.Foreign.HSLedger
import Ledger.Foreign.LedgerTypes
import Ledger.Ledger
import Ledger.NewPP
import Ledger.PDF
import Ledger.PPUp
import Ledger.PParams
import Ledger.Prelude
import Ledger.Script
import Ledger.Transaction
import Ledger.Utxo
import Ledger.Utxo.Properties
import Ledger.Utxow
import Ledger.Utxow.Properties
import MidnightExample.HSLedger
import MidnightExample.Ledger
import MidnightExample.PDF
import MidnightExample.Types
import MyDebugOptions
import Prelude
import PreludeImports
import Tactic.DeriveComp
import Test.GetType
```

and this file (hence all the imported modules) type-check.

**Pull request merged**
