### PR TITLE
Remove the old Computational in favour of the new representation

### LINKED ISSUE #211: Should we use `Computational'` everywhere instead of `Computational`?
Since we now use `Computational'` for defining all the instances, it may be worth switching everything to `Computational'`. `Computational` is still at least good for presentation, but we can look into replacing it everywhere else.

### PR DESCRIPTION
**Pull request by UlfNorell**
Also
- make SS⇒BS more amenable to instance search
- cleaned up Computational instance for LEDGER

Fixes #211

### CODE REVIEW

**Comment by UlfNorell** [comment]
@WhatisRT this is now rebased on master

**Comment by omelkonian** [comment]
Oops, I broke it again..

**Comment by omelkonian** [comment]
OK the error makes sense, it's complaining that `Tactic.DeriveComp` is not used anymore (the check done by `checkTypechecked.sh`). I will push a quick fix that imports it in `Ledger.Prelude` for now.

**Review by omelkonian — APPROVED** [review]
LGTM; I've just refactored the computational proof in `Ledger.Properties` to avoid code duplication and removed obsolete imports to `Tactic.DeriveComp` (but we still need a dummy import in `Ledger.Prelude` to keep it around past CI checks).

**Pull request merged**
