### PR TITLE
Various cleanup items: Fig 12 -- axiomatic rules

### PR DESCRIPTION
**Pull request by williamdemeo**
# Description

This addresses one issue of #288.

We could explain that some rules have no premise (they're essentially axioms). Instead, for consistency, we simply define a horizontal line that takes no premise, introducing syntax to represent such "axiomatic" rules.

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/CONTRIBUTING.md)
- [X] Self-reviewed the diff

### CODE REVIEW

**Comment by omelkonian** [comment]
This is somewhat overlapping with #268 , which also introduces the "axiom" syntax and a slightly different represent of premises (= uncurried = single argument as a tuple of premises).

**Comment by omelkonian** [comment]
@williamdemeo Since #268 will be merged today probably, I would suggest rebasing now so that you don't spend time repeating the same definitions or resolving merge conflicts.

**Comment by WhatisRT** [comment]
Indeed, I think this is the correct approach, but it's probably best to get in #268 first

**Comment by williamdemeo** [comment]
Okay, I think we're good to go.  @WhatisRT please take a look so we can GTM.  Thanks!

**Review by WhatisRT — APPROVED** [review]
LGTM

**Pull request merged**
