### PR TITLE
Prove POV and computational for LEDGERS

### PR DESCRIPTION
**Pull request by WhatisRT**

### CODE REVIEW

**Review by Ali-Hill — COMMENTED** [review]
This all looks good to me. We will need to look at how best to merge multi-asset with the notion of HasCoin in this pull request but I don't think it will be too difficult. I will approve this once I have gotten it to type check.

**Comment by Ali-Hill** [comment]
> This all looks good to me. We will need to look at how best to merge multi-asset with the notion of HasCoin in this pull request but I don't think it will be too difficult. I will approve this once I have gotten it to type check.

**Review by Ali-Hill — APPROVED** [review]
This now builds and type checks for me.

**Review by Ali-Hill — CHANGES_REQUESTED** [review]
I have two changes: 
1. Ledger/PPUp/Properties.agda does not type check for me 
2. I didn't catch this originally as this file was not checked in the Everything.agda file

**Comment by WhatisRT** [comment]
Good find! I changed notation at some point (from 1# + 1# to 2 via literal overloading) and those two weren't definitionally equal and I didn't adjust it everywhere. It's fixed now.

**Review by Ali-Hill — APPROVED** [review]

**Comment by Ali-Hill** [comment]
Everything type-checks for me now. The only files that are not type-checked by everything are the ones that we fixed in the master branch already.

**Comment by williamdemeo** [comment]
Everything type-checks for me except the file `src/Interface/Show.agda`.  There's an ambiguity. (I suspect you added a module called `Show` to stdlib-meta and perhaps we don't need `src/Interface/Show.agda` anymore...?)

Here's the error:
```
/formal-ledger-specifications/src/Interface/Show.agda:3,8-22
Ambiguous module name. The module name Interface.Show could refer
to any of the following files:
  /nix/store/qnbpy249pdvqnr152sd2ffqw946qipyw-agda-stdlib-meta-0.1/Interface/Show.agda
  /formal-ledger-specifications/src/Interface/Show.agda
```

**Comment by WhatisRT** [comment]
Yeah, this was just a leftover and already has been removed from `master`, and it'll disappear with the rebase.

**Pull request merged**
